#ifndef _MLX90642_COMMANDS_HPP_
#define _MLX90642_COMMANDS_HPP_

#define INVALID_VALUE -1

#define REG_FIRMWARE_MAJOR 0xFFF8
#define REG_FIRMWARE_MINOR_PATCH 0xFFFA

// config addresses
#define CONFIGURATION_CMD 0x3A2E
#define CONFIG_ADDR_REFRESH_RATE_CONFIG  0x11F0
#define CONFIG_ADDR_EMISSIVITY  0x11F2
#define CONFIG_ADDR_APPLICATION_CONFIG  0x11F4
#define CONFIG_ADDR_I2C_ANALOG_CONFIG  0x11FC
#define CONFIG_ADDR_I2C_CONFIG  0x11FE
#define CONFIG_ADDR_BACKGROUND_TEMP  0xEEEE // set by user

// masks
#define REFRESH_RATE_MASK       0x0007
#define EMISSIVITY_MASK         0xFFFF
#define MEASURING_MODE_MASK     0x0800
#define OUTPUT_DATA_FORMAT_MASK 0x0100
#define REFERRED_U_THRESHOLD_MASK 0x0004
#define CURRENT_LIMIT_MASK      0x0002
#define FM_MODE_MASK            0x0001
#define I2C_MASK                0x007F
#define BACKGROUND_TEMP_MASK    0xFFFF

// refresh rate
#define REFRESH_RATE_2_HZ   0x0002
#define REFRESH_RATE_4_HZ   0x0003
#define REFRESH_RATE_8_HZ   0x0004
#define REFRESH_RATE_16_HZ  0x0005

// measuring mode
#define STEP_MEASURING_MODE 0x0800
#define CONT_MEASURING_MODE 0x0000

// output data
#define OUTPUT_DATA_ABSOLUTE 0x0000
#define OUTPUT_DATA_NORMALIZED 0x0100

//ref U threshold
#define VDD_REFFERED_THRESH 0x0
#define U1_8_REFFERED_THRESH 0x1

// current limit
#define CURRENT_LIMIT_ENABLED 0x0
#define CURRENT_LIMIT_DISABLED 0x1

// cm mode
#define FM_MODE_ENABLED 0x0
#define FM_MODE_DISABLED 0x1

// progress bar
#define REG_PROGRESS_BAR 0x3C10

#define PROGRESS_BAR_MASK 0x00ff

// data flags
#define REG_DATA_FLAGS 0x3C14

#define FRAME_UPDATE_FLAG_MASK  0x0200
#define READY_FLAG_MASK         0x0100
#define BUSY_FLAG_MASK          0x0001

//reading pixels
#define PIXEL_ADDR_START 0x342C
#define PIXEL_ADDR_STOP  0x3A2A


#define PIXEL_WIDTH 32
#define PIXEL_HEIGHT 24
#define WORD_LENGTH_BYTES 2

#define PIXEL_COUNT_BYTES PIXEL_WIDTH * PIXEL_HEIGHT * WORD_LENGTH_BYTES //1536
#define PIXEL_READ_CHUNK_BYTES 256
#define CHUNK_COUNT PIXEL_COUNT_BYTES / PIXEL_READ_CHUNK_BYTES



#endif /* _MLX90642_COMMANDS_HPP_ */